### ISSUE TITLE
Clean up styling on Filter

### ISSUE THREAD

**Issue by nguyenq9** [nguyenq9/EpistimisLLC#26]
Make the filter component fit stylistically with the rest of the page.

**Comment by nguyenq9** [comment]
@karpej I think the options shouldn't be underlined. It looks a bit clunky with the underline since the categories are so long.

**Comment by karpej** [comment]
Okay no worries, I’ll push the updated filter when I get back from lab it
looks way better, and then we can take out the underlines , but I’ll let
you check it out how it is right now updated

**Comment by steve-hickman-epistimis** [comment]
The filter drop down could expand to the left when it drops down if you want to avoid line wrapping each of the choices.

**Comment by steve-hickman-epistimis** [comment]
Can you make it clear what is a submenu of what? Also, what about boolean algebra support for filters?  

Also, the filters remain active when comparing between states. Is that what you want? Develop a philosophy about how features interact with each other and document it for users so they know what to expect.  It doesn't matter what that philosophy is as long as you can create a sensical argument for it.
