### ISSUE TITLE
wraparound map scrolling?

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [nguyenq9/EpistimisLLC#40]
The world map view currently only allows for the Americas to display on the left, with Africa/Europe/Asia/Australia on the right. This means a comparison between New Zealand and Alaska requires traversing a long way across the map. Are you going to make it possible to scroll right and left so that the Americas could appear somewhere other than on the left side of the map?

**Comment by nguyenq9** [comment]
The package our map is from currently doesn't support wraparound map scrolling
